### ISSUE TITLE
Update Hacktoberfest 2021 Repos For Hacktoberfest 2022

### ISSUE THREAD

**Issue by Bobliuuu** [vivian-dai/Hacktoberfest-2022-Repos#112] opened 2022-09-29 13:35 UTC
Go through the current Hacktoberfest active repos, and move any inactive or not tagged repos (without the hacktoberfest-2022 tag) to the inactive or invalid list.

**Comment by vivian-dai** [comment] 2022-09-29 17:06
@chiragkhatri19 you can just take the issue. If the issue is broad enough (like this one) anyone can take it. I will only be assigning specific issues

**Comment by chiragkhatri19** [comment] 2022-09-30 00:54
Got it @vivian-dai

**Comment by Nithin108** [comment] 2022-10-01 05:52
assign this to me please

**Comment by vivian-dai** [comment] 2022-10-01 11:49
@Nithin108 just take the issue, see comment above

**Closed** 2022-11-01 16:06 UTC
Labels: enhancement, help wanted, good first issue, hacktoberfest
